eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://192.168.230.129:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: my-kafka-producer
  kafka:
    producer:
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      bootstrap-servers: 192.168.0.17:9092
    consumer:
      bootstrap-servers: 192.168.0.17:9092
      group-id: test
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
zookeeper:
  connect: 192.168.0.235:2181
