eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.20.17:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: my-eureka-server